const actionTypes = {
  ADD_TODO: "ADD_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  TOGGLE_TODO: "TOGGLE_TODO",
  RESET_TODO: "RESET_TODO",
  INITIAL_FETCH: "INITIAL_FETCH",
  DISPATCH_ERROR: "DISPATCH_ERROR",
};

export default actionTypes;
